#!/bin/bash

#SBATCH --nodes 4
#SBATCH --ntasks-per-node 1
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --job-name MPI
#SBATCH --time 00:15:00
#SBATCH --output OUT3
#SBATCH --exclusive

# This time, asking for 1 node with 4 tasks per node

# Use Intel MPI (make sure you compile with the same module and 'mpiicc')
module load languages/intel/2018-u3


# Print some information about the job
echo "Running on host $(hostname)"
echo "Time is $(date)"
echo "Directory is $(pwd)"
echo "Slurm job ID is $SLURM_JOB_ID"
echo
echo "This job runs on the following machines:"
echo "$SLURM_JOB_NODELIST" | uniq
echo


# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

# Run the parallel MPI executable
# Just run the first binary: change this line to try out the others
mpirun -np 4 ./skeleton2-simple2d.exe

